# 数据库的连接信息
spring:
  application:
    name: zzy-third
  cloud:
    alicloud:
      access-key: LTAI5tBZcnJqZn4zqDGtiwkG
      secret-key: zS2RNYlJpjs8tI0kQX3pkITZ3vwFx9
      oss:
        endpoint: oss-cn-wuhan-lr.aliyuncs.com
        bucket: zhouziyang-mall
      sms:
        host: https://wwsms.market.alicloudapi.com
        path: /send_sms
        method: POST
        appcode: 0de38643bd414257801a01c957337d7b
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.56.100:8858
        client-ip: 192.168.146.1

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: "*"