# 数据库的连接信息
spring:
  application:
    name: zzy-third
  cloud:
    alicloud:
      access-key: LTAI5tBZcnJqZn4zqDGtiwkG
      secret-key: zS2RNYlJpjs8tI0kQX3pkITZ3vwFx9
      oss:
        endpoint: oss-cn-wuhan-lr.aliyuncs.com
        bucket: zhouziyang-mall
      sms:
        host: https://wwsms.market.alicloudapi.com
        path: /send_sms
        method: POST
        appcode: 0de38643bd414257801a01c957337d7b

server:
  port: 8090