# 注册中心的配置
spring:
  cloud:
    gateway:
      routes:
        - id: product-route
          uri: lb://zzy-product
          predicates:
            - Path=/app/product/**
          filters:
            - StripPrefix=1
        - id: third-route
          uri: lb://zzy-third
          predicates:
            - Path=/app/third/**
          filters:
            - StripPrefix=2
        - id: member-route
          uri: lb://zzy-member
          predicates:
            - Path=/app/member/**
          filters:
            - StripPrefix=1
        - id: ware-route
          uri: lb://zzy-ware
          predicates:
            - Path=/app/ware/**
          filters:
            - StripPrefix=1
        - id: coupon-route
          uri: lb://zzy-coupon
          predicates:
            - Path=/app/coupon/**
          filters:
            - StripPrefix=1
        - id: app-route
          uri: lb://renren-fast
          predicates:
            - Path=/app/**
          filters:
            - RewritePath=/app/(?<segment>/?.*),/renren-fast/$\{segment}
          # localhost:8070/app/captcha.jpg --> localhost:8080/app/captcha.ipg --> localhost:8080/renren-fast/captcha.ipg
        - id: zzy-mall-route
          uri: lb://zzy-product
          predicates:
            - Host=**.mall.zzy.com,**.item.zzy.com
        - id: zzy-search-route
          uri: lb://zzy-search
          predicates:
            - Host=**.search.zzy.com
        - id: zzy-auth-route
          uri: lb://zzy-auth
          predicates:
            - Host=**.auth.zzy.com
        - id: zzy-cart-route
          uri: lb://zzy-cart
          predicates:
            - Host=**.cart.zzy.com
        - id: zzy-order-route
          uri: lb://zzy-order
          predicates:
            - Host=**.order.zzy.com
        - id: zzy-seckill-route
          uri: lb://zzy-seckill
          predicates:
            - Host=**.seckill.zzy.com
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.56.100:8858
        client-ip: 192.168.146.1
  application:
    name: zzy-gateway

server:
  port: 8070

management:
  endpoints:
    web:
      exposure:
        include: "*"
