# 注册中心的配置
spring:
  cloud:
    gateway:
      routes:
        - id: product-route
          uri: lb://zzy-product
          predicates:
            - Path=/app/product/**
          filters:
            - StripPrefix=1
        - id: third-route
          uri: lb://zzy-third
          predicates:
            - Path=/app/third/**
          filters:
            - StripPrefix=2
        - id: member-route
          uri: lb://zzy-member
          predicates:
            - Path=/app/member/**
          filters:
            - StripPrefix=1
        - id: ware-route
          uri: lb://zzy-ware
          predicates:
            - Path=/app/ware/**
          filters:
            - StripPrefix=1
        - id: app-route
          uri: lb://renren-fast
          predicates:
            - Path=/app/**
          filters:
            - RewritePath=/app/(?<segment>/?.*),/renren-fast/$\{segment}
          # localhost:8070/app/captcha.jpg --> localhost:8080/app/captcha.ipg --> localhost:8080/renren-fast/captcha.ipg
        - id: zzy-mall-route
          uri: lb://zzy-product
          predicates:
            - Host=**.zzy.mall.com
        - id: zzy-search-route
          uri: lb://zzy-search
          predicates:
            - Host=**.zzy.search.com
  application:
    name: zzy-gateway

server:
  port: 8070