spring:
  application:
    name: zzy-search
  # 设置服务器响应给客户端的日期时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  session:
    store-type: redis
    redis:
      namespace: spring:session
    timeout: 30m
  redis:
    host: 192.168.56.100
    port: 6379

server:
  port: 8100