spring:
  application:
    name: zzy-search
  # 设置服务器响应给客户端的日期时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  session:
    store-type: redis
    redis:
      namespace: spring:session
    timeout: 30m
  redis:
    host: 192.168.56.100
    port: 6379
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.56.100:8858
        client-ip: 192.168.146.1

server:
  port: 8100

management:
  endpoints:
    web:
      exposure:
        include: "*"