# 数据库的连接信息
spring:
  application:
    name: zzy-auth
  # 设置服务器响应给客户端的日期时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false # 关闭thymeleaf默认缓存
  redis:
    host: 192.168.56.100
    port: 6379
  session:
    store-type: redis
    timeout: 30m
    redis:
      namespace: spring:session
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.56.100:8858
        client-ip: 192.168.146.1

server:
  port: 30000
  servlet:
    session:
      timeout: 30m # session 过期时间

management:
  endpoints:
    web:
      exposure:
        include: "*"