# 数据库的连接信息
spring:
  application:
    name: zzy-cart
  # 设置服务器响应给客户端的日期时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false # 关闭thymeleaf默认缓存
  redis:
    host: 192.168.56.100
    port: 6379
  session:
    store-type: redis
    timeout: 30m
    redis:
      namespace: spring:session

server:
  port: 40000